name: Build and Deploy (Vite/pnpm - FINAL)

on:
  push:
    branches: ["main"]

  # Permite rodar manualmente através da aba Actions
  workflow_dispatch:

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Usando versão 20 (compatível com pnpm)
          cache: 'npm' # Mudamos para 'npm' pois instalaremos o pnpm via npm

      # VVVV PASSO CRUCIAL: INSTALAÇÃO GARANTIDA DO PNPM VVVV
      - name: Install pnpm globally (Solução para o Erro 'Unable to locate pnpm')
        run: npm install -g pnpm 
      # ^^^^ FIM DO PASSO DE CORREÇÃO ^^^^
      
      - name: Install dependencies (usando pnpm)
        # O pnpm já está disponível globalmente graças ao passo anterior
        run: pnpm install --frozen-lockfile

      - name: Build project (pnpm run build)
        run: pnpm run build
        
      # Configura o ambiente de publicação do GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          # Define que a pasta a ser publicada é a 'dist' (saída do Vite)
          static_site_artifact_path: './dist' 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
